# Generated by Django 4.2.2 on 2024-09-29 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('first_sending', models.DateField(help_text='дата и время первой отправки рассылки', verbose_name='первая отправка')),
                ('interval', models.CharField(choices=[('minute', 'Раз в минуту'), ('day', 'Раз в день'), ('week', 'Раз в неделю'), ('month', 'Раз в месяц')], default='month', max_length=15, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('off', 'Отключена'), ('waiting_first', 'Запущена, Ожидает первой отправки'), ('send_waiting', 'Отправлена, ожидает следующей отправки')], default='off', max_length=15, verbose_name='статус')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_message', to='mailings.message', verbose_name='сообщение рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='mailing',
            field=models.ManyToManyField(related_name='client_mailings', to='mailings.mailing', verbose_name='рассылки клиента'),
        ),
    ]
