# Generated by Django 4.2.2 on 2024-09-29 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_mailing_client_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_count', models.PositiveIntegerField(default=0, verbose_name='попыток рассылки')),
                ('last_try', models.DateField(help_text='дата и время последней попытки', verbose_name='последняя попытка')),
                ('try_status', models.BooleanField(default=False, verbose_name='статус попытки')),
                ('email_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('try_number', models.CharField(max_length=100, verbose_name='номер попытки')),
            ],
            options={
                'verbose_name': 'попытка рассылки',
                'verbose_name_plural': 'попытки рассылки',
                'ordering': ('try_number',),
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='mailing_try',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_tries', to='mailings.mailingtry', verbose_name='попытки рассылки'),
        ),
    ]
