# Generated by Django 4.2.2 on 2024-09-30 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_remove_client_mailing_mailing_clients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('first_sending',), 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingtry',
            options={'ordering': ('try_number', 'last_try'), 'verbose_name': 'попытка рассылки', 'verbose_name_plural': 'попытки рассылки'},
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='mailing_try',
        ),
        migrations.AddField(
            model_name='mailingtry',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tries_mailing', to='mailings.mailing', verbose_name='рассылка попытки'),
        ),
    ]
