# Generated by Django 4.2.2 on 2024-10-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0007_alter_mailingtry_options_remove_mailingtry_try_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('first_sending',), 'permissions': [('change_status', 'Can change status of mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
