# Generated by Django 4.2.2 on 2024-10-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0009_mailing_last_sending_alter_client_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingtry',
            name='last_try',
            field=models.DateTimeField(help_text='дата и время последней попытки', verbose_name='последняя попытка'),
        ),
        migrations.AlterField(
            model_name='mailingtry',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tries_mailing', to='mailings.mailing', verbose_name='рассылка попытки'),
        ),
    ]
