# Generated by Django 4.2.2 on 2024-10-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0010_alter_mailingtry_last_try_alter_mailingtry_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingtry',
            name='last_try',
            field=models.DateTimeField(auto_now=True, help_text='дата и время последней попытки', verbose_name='последняя попытка'),
        ),
    ]
