# Generated by Django 4.2.2 on 2024-10-10 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0011_alter_mailingtry_last_try'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingtry',
            options={'ordering': ('last_try',), 'verbose_name': 'попытка рассылки', 'verbose_name_plural': 'попытки рассылки'},
        ),
        migrations.RemoveField(
            model_name='mailingtry',
            name='name',
        ),
    ]
