# Generated by Django 4.2.2 on 2024-10-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0012_alter_mailingtry_options_remove_mailingtry_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='last_sending',
        ),
        migrations.AddField(
            model_name='mailing',
            name='next_sending',
            field=models.DateTimeField(blank=True, null=True, verbose_name='следующая отправка'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='first_sending',
            field=models.DateTimeField(help_text='дата и время первой отправки', verbose_name='первая отправка'),
        ),
    ]
