# Generated by Django 4.2.2 on 2024-10-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0013_remove_mailing_last_sending_mailing_next_sending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='last_sending',
            field=models.DateTimeField(blank=True, null=True, verbose_name='крайняя отправка'),
        ),
    ]
