# Generated by Django 4.2.2 on 2024-10-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0014_mailing_last_sending'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('next_sending',), 'permissions': [('change_status', 'Can change status of mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='first_sending',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='next_sending',
            field=models.DateTimeField(blank=True, help_text='ГГГГ-ММ-ДД ЧЧ:ММ:СС', null=True, verbose_name='дата и время отправки'),
        ),
    ]
