# Generated by Django 4.2.2 on 2024-10-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0015_alter_mailing_options_remove_mailing_first_sending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='interval',
            field=models.CharField(choices=[('day', 'Раз в день'), ('week', 'Раз в неделю'), ('month', 'Раз в месяц')], default='month', max_length=15, verbose_name='периодичность'),
        ),
    ]
